import React, { Component } from 'react'
import './index.css'

class Tokenomic extends Component {
    render() {
        return (
            <div className="tokenomicssection">
               <h1 id="tokenomicsSection" className="section-heading">Tokenomics</h1>

                <div className="tokenomics wf-section">


                    <div className="tokenomics-container w-container">
                        <div className="grid grid-cols-5 text-white">
                            <div className="">
                                <img src="/images/eth.svg" loading="lazy" width="57" style={{opacity: 1}} data-w-id="0525b926-abae-7cf3-a3da-a9886f3b4de0" alt="Ethereum Logo" className="image-16" />
                            </div>
                            <div className="col-span-4">
                                <h2><span className="text-span w-clearfix text-white"><strong className="heading3" style={{opacity: 1, fontSize: '32px'}}>Ethereum Smart Contract</strong></span></h2>
                                <div className="stretchgoalcontent mt-6" style={{opacity: 1}}>
                                    Built on the ERC-721 Non-Fungible Token Standard, The Rubber Duck can be owned by anyone with an Ethereum Wallet address.<br/><br/>RubberDucks are fully transferrable and tradeable on platforms such as Open Sea.
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="tokenomics-container w-container">
                        <div className="grid grid-cols-5 text-white">
                            <div className="">
                                <img src="/images/ducka.png" loading="lazy" width="57" style={{opacity: 1}} data-w-id="0525b926-abae-7cf3-a3da-a9886f3b4de0" alt="Ethereum Logo" className="image-16" />
                            </div>
                            <div className="col-span-4">
                                <h2><span className="text-span w-clearfix text-white"><strong className="heading3" style={{opacity: 1, fontSize: '32px'}}>10,000 Rubber Ducks
                                </strong></span></h2>
                                <div className="stretchgoalcontent mt-6" style={{opacity: 1}}>
                                Rubber Ducks are programmatically generated by a random combination of 130+ traits. These traits make each rubber duck unique and identifiable.<br/>Each rubber duck are designed in 3D,<br/><br/>100 boxed RubberDucks are reserved for core team, giveaways and future promos.
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="tokenomics-container w-container">
                        <div className="grid grid-cols-5 text-white">
                            <div className="">
                                <img src="/images/metamask.svg" loading="lazy" width="57" style={{opacity: 1}} data-w-id="0525b926-abae-7cf3-a3da-a9886f3b4de0" alt="Ethereum Logo" className="image-16" />
                            </div>
                            <div className="col-span-4">
                                <h2><span className="text-span w-clearfix text-white"><strong className="heading3" style={{opacity: 1, fontSize: '32px'}}>0,025 ETH Pre-Sale Price

                                </strong></span></h2>
                                <div className="stretchgoalcontent mt-6" style={{opacity: 1}}>
                                Rubber Ducks are Mintable at 0.025 ETH (excluding Gas cost) starting 17th October 2021. You can mint 20 per transaction.
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="tokenomics-container w-container">
                        <div className="grid grid-cols-5 text-white">
                            <div className="">
                                <img src="/images/ipfs.png" loading="lazy" width="57" style={{opacity: 1}} data-w-id="0525b926-abae-7cf3-a3da-a9886f3b4de0" alt="Ethereum Logo" className="image-16" />
                            </div>
                            <div className="col-span-4">
                                <h2><span className="text-span w-clearfix text-white"><strong className="heading3" style={{opacity: 1, fontSize: '32px'}}>InterPlanetary File System

                                </strong></span></h2>
                                <div className="stretchgoalcontent mt-6" style={{opacity: 1}}>
                                The IPFS is a peer-to-peer network for storing and sharing data. This means RubberDucks are decentralised and not soley on any one website or server.
                                </div>
                            </div>
                        </div>
                    </div>

                    
                </div>

                <div className="d-block mt-10">
                    <hr />
                </div>
            </div>
        )
    }
}

export default Tokenomic